### PR TITLE
Added getOrderID method to Icepay_TransactionObject.

### PR DESCRIPTION
**Pull request by xavierbarbosa**
This is useful so we can keep track of what stage the user is in for an order on our side.

### CODE REVIEW

**Comment by RicardoJ** [comment]
This looks like a very good feature for this webservice client. Can you also provide us with an example file (```track_payment``` for example) in the [samples/](https://github.com/icepay/icepay/tree/develop/samples) folder that explains and demo-ish this feature?

If you do so, just commit those changes against [your fork](https://github.com/xavierbarbosa/icepay/tree/develop/samples) and pull request them back so it stays within one pull request to keep the environment and repository clean :blush:

I am also currently updating the documentation on the website due to the last changes in this repository and I'd be happy to include your changes and example within the documentation release this week.

:+1:

**Comment by xavierbarbosa** [comment]
Hi Ricardo,

Thank you for you consideration. I have added an example like you requested.

**Comment by RicardoJ** [comment]
Hi xavierbarbosa,

I merged your pull request into the develop branch.

**Comment by xavierbarbosa** [comment]
Neat!

**Pull request merged**
